//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string ActivityDescription { get; set; }
        public string ProjectStatus { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string TaskStatus { get; set; }
        public string Operation { get; set; }
        public System.DateTime ActivityDate { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
